### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [L4ser-Security-Labs/whoget#3]
hi, I've problem with start

whoget$ python3 whoget.py
Traceback (most recent call last):
  File "whoget.py", line 29, in <module>
    import social
  File "src/social.py", line 31, in <module>
    TWITTER_API_KEY=config('vAVbhh4kv8U0bgTwX7X0cV')
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: vAVbhh4kv8U0bgTwX7X0cV not found. Declare it as envvar or define a default value.

can you help?

**Comment by lagosnomad** [comment]
hi,

have you created the .env file with your keys?

**Comment by shanow7** [comment]
I don't know how to do this, but I use api key in social.py

**Comment by lagosnomad** [comment]
@shanow7 please share your environment details while I try to reproduce this

thanks

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/88087515-54176980-cb89-11ea-94da-30a8a9546381.png)

is this correct? and how can i sign up?

**Comment by lagosnomad** [comment]
To obtain your Twitter keys, check the [**How to get started with the Twitter APIs**](https://developer.twitter.com/en/docs/basics/getting-started) section.

To obtain your Facebook keys [follow this link](https://developers.facebook.com/tools/accesstoken)

**Comment by shanow7** [comment]
we did not understand each other...
I have the keys, I asked if they were entered correctly in .env and if so, with what command to save the file

**Comment by lagosnomad** [comment]
yes you've entered correctly. I can see you're using Vim so use the command ":x" to save

**Comment by shanow7** [comment]
~/OSINT/whoget$ python3 whoget.py -p +2348123456789
Traceback (most recent call last):
  File "whoget.py", line 29, in <module>
    import social
  File "src/social.py", line 31, in <module>
    TWITTER_API_KEY=config('vAVbhh4kvzfv8U0bg')
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: vAVbhh4kvzfv8U0bg not found. Declare it as envvar or define a default value.

**Comment by lagosnomad** [comment]
TWITTER_API_KEY=config('vAVbhh4kvzfv8U0bg')
That is the wrong format for defining your keys.

Please follow the `.env` setup guide [here](https://github.com/L4ser-Security-Labs/whoget#setup-api-keys) and let me know if you still have the error.

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/89124779-e862c400-d4d9-11ea-82fa-ff51196a51a1.png)
I heve this format is wrong?

**Comment by lagosnomad** [comment]
please send me an email wole[at]lagosnomad[dot]com so I can help you debug this issue closely since I can't reproduce.
